# permissions for end users to view edgices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgex-viewer-role
rules:
- apiGroups:
  - edgex.deploy
  resources:
  - edgices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edgex.deploy
  resources:
  - edgices/status
  verbs:
  - get
